services:
  rating-api:
    image: rating-api
    build:
      context: .               
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env 
    volumes:
      - ./upload:/usr/src/app/upload
